config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  root 'home#home'
  get '/settings', to: 'admin#settings'
  get '/create', to: 'patrons#new'
  post '/create', to: 'patrons#create'
  get '/createOrder', to: 'orders#new'
  post '/createOrder', to: 'orders#create'
  get '/edit', to: 'orders#edit'
  get '/viewOrders', to: 'orders#viewOrders'
  
  resources :orders, :patrons, :posters, :threedprints
  
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  #belongs_to :patrons
  has_many :posters, dependent: :destroy
  has_many :threedprints, dependent: :destroy
  accepts_nested_attributes_for :posters, :allow_destroy => true
  accepts_nested_attributes_for :threedprints, :allow_destroy => true
  #accepts_nested_attributes_for :patrons 
  
  default_scope -> { order(created_at: :desc) }
  validates :patron_id, presence: true, length: {maximum: 30}
  validates :print_location, presence: true, length: {maximum: 30}
  validates :payment, presence: true, length: {maximum: 30}
  validates :status, presence: true, length: {maximum: 30}
  validates :staff_print, presence: true, length: {maximum: 30}
  validates :takenby, presence: true, length: {maximum: 30}
end

app/models/patron.rb
class Patron < ApplicationRecord
  has_many :orders
  
  before_save {self.email = email.downcase}
  before_save {self.first_name = first_name.slice(0,1).capitalize + first_name.slice(1..-1).downcase}
  before_save {self.last_name = last_name.slice(0,1).capitalize + last_name.slice(1..-1).downcase}
  
  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 30}
  
  ##TODO: Add so Phone Regex Takes "/" inbetween characters
    #Or have form automatcially create 3 boxes with - between
  VALID_PHONE_REGEX = /\A\(?\d{3}\)?[- ]?\d{3}[- ]?\d{4}\z/
  validates :phone, presence: true, length: {maximum: 20},
                    format: { with: VALID_PHONE_REGEX}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false}
  ##has_secure_password
  
  ##validates :password, length: { minimum: 6 }
end

app/models/poster.rb
class Poster < ApplicationRecord
  belongs_to :order
  
  default_scope -> { order(created_at: :desc) }
  validates :file_name, presence: true, length: {maximum: 30}
  validates :patron_id, presence: true, length: {maximum: 20}
  validates :quantity, presence: true, length: {maximum: 30}
  validates :price, presence: true, length: {maximum: 30}
  validates :width, presence: true, length: {maximum: 30}
  validates :height, presence: true, length: {maximum: 30}
  validates :price_per_sqft, presence: true, length: {maximum: 30}
  validates :paper_type, presence: true, length: {maximum: 30}
  #NO VALIDATION FOR COMMENTS
end

app/models/threedprint.rb
class Threedprint < ApplicationRecord
  belongs_to :order
  
  default_scope -> { order(created_at: :desc) }
  validates :file_name, presence: true, length: {maximum: 30}
  validates :quantity, presence: true, length: {maximum: 30}
  validates :price, presence: true, length: {maximum: 30}
  validates :price_per_m, presence: true, length: {maximum: 30}
  validates :color, presence: true, length: {maximum: 30}
  validates :scaling, presence: true, length: {maximum: 30}
  validates :platform_adhesion, presence: true, length: {maximum: 30}
  validates :supports, presence: true, length: {maximum: 30}
  #NO VALIDATION FOR COMMENTS
end

app/controllers/admin_controller.rb
class AdminController< ApplicationController
  def settings
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #Original call for order forms
  def new
    @order = Order.new
    1.times {@order.posters.build}
  end
  
  def show
  end

  def index
    @orders = Order.all
  end
  
  #Order forms that don't have all required fields
  def create
    @order = Order.create(order_params)
    
    if @order.save
      #handle save
      flash[:success] = "Order Created Sucessfully!"
      redirect_to viewOrders_path
    else
      render 'new'
    end
    
  end
  
  def edit
    @order = Order.find(params[:id])
  end 
  
  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(order_params)
      # Handle a successful update.
      flash[:success] = "Order Updated Sucessfully!"
      redirect_to viewOrders_path
    else
      render 'edit'
    end
  end
    
  def destroy
    Order.find(params[:id]).destroy
    flash[:success] = "Order Deleted Sucessfully!"
    redirect_to viewOrders_path
  end

  def viewOrders
    @orders = Order.all
  end
  
  
  
  private
  
    def order_params
      params.require(:order).permit(:patron_id, :print_location, :payment, :status, :staff_print, :takenby,
      posters_attributes:[:file_name, :patron_id, :quantity, :price, :width, :height, :comments, :price_per_sqft, :paper_type, :id])
    end
    
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController
  def new
    @patron = Patron.new
  end

  #Order forms that don't have all required fields
  def create
    @patron = Patron.create(patron_params)
    
    if @patron.save
      #handle save
      flash[:success] = "Patron Created Sucessfully!"
      redirect_to createOrder_path
    else
      render 'new'
    end
    
  end
  
  private
  
    def patron_params
      params.require(:patron).permit(:id, :first_name, :last_name, :phone, :email)
    end
    
  
end

app/helpers/admin_controller_helper.rb
module AdminControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Poster Tracking System"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_controller_helper.rb
module HomeControllerHelper
end

app/helpers/orders_controller_helper.rb
module OrdersControllerHelper
end

app/helpers/patron_helper.rb
module PatronHelper
end

app/views/admin/settings.html.erb
<h1>AdminController#settings</h1>
<p>Find me in app/views/admin_controller/settings.html.erb</p>

app/views/home/home.html.erb
<div class="center jumbotron">
  <h1>Poster Tracking System</h1>

  <h2>
    This is the home page for the Poster Tracking System application.
  </h2>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    College Library | Computer and Media Center | Poster Tracking System
  </small>
  <nav>
    <ul>
      <!-- Links for Navigation here --> 
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Poster Tracking System", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Create", create_path   %></li>
        <li><%= link_to "View Orders", viewOrders_path %></li>
        <li><%= link_to "Settings", settings_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/orders/_order.html.erb
<li>
  <%= content_tag :table, data:{url: viewOrders_path(format: :json)} do %>
    <thead>
      <tr>
        <th> OrderID </th>
        <th> print_location</th>
        <th> status </th>
        <th> payment </th>
        <th> takenby </th>
        <th colspan="2"></th>
      </tr>
    </thead>
    
    <tbody>
      
    </tbody>
  <%end%>
  
</li> 

app/views/orders/edit.html.erb
<% provide(:title, "Edit Order") %>
<h1>Edit Order</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@order) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :patron_id %>
      <%= f.text_field :patron_id, class: 'form_control' %>

      <%= f.label :print_location %>
      <%= f.text_field :print_location, class: 'form_control' %>
      
      <%= f.label :payment %>
      <%= f.text_field :payment, class: 'form_control' %>
      
      <%= f.label :status %>
      <%= f.text_field :status, class: 'form_control' %>
      
      <%= f.label :staff_print %>
      <%= f.text_field :staff_print, class: 'form_control' %>
      
      <%= f.label :takenby %>
      <%= f.text_field :takenby, class: 'form_control' %>


      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
    <%= link_to "Delete Order", @order, method: :delete,
                                  data: { confirm: "Are you sure you wish to delete this Order?" } %>
  </div>
</div>

app/views/orders/new.html.erb
<% provide(:title, 'New Order') %>
<h1>Create New Order</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@order, url: createOrder_path) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :patron_id %>
      <%= f.text_field :patron_id, class: 'form_control' %>

      <%= f.label :print_location %>
      <%= f.select :print_location, ['College', 'Steenbock'], class: 'form_control' %>
      
      <%= f.label :payment %>
      <%= f.select :print_location, ['Personal Credit', 'Wiscard', 'Print Card', 'Funding String'], class: 'form_control' %>
      
      <%= f.label :status %>
      <%= f.text_field :status, class: 'form_control' %>
      
      <%= f.label :staff_print %>
      <%= f.select :staff_print, ['No', 'Staff Print'], class 'form_control' %>
      
      <%= f.label :takenby %>
      <%= f.text_field :takenby, class: 'form_control' %>
      
      <%= f.nested_fields_for :posters do |poster_form| %>
        
          <%= poster_form.label :file_name %>
          <%= poster_form.text_field :file_name, class: 'form_control' %>
          
          <%= poster_form.label :patron_id %>
          <%= poster_form.text_field :patron_id, class: 'form_control' %>
          
          <%= poster_form.label :quantity %>
          <%= poster_form.text_field :quantity, class: 'form_control' %>
          
          <%= poster_form.label :price %>
          <%= poster_form.text_field :price, class: 'form_control' %>
          
          <%= poster_form.label :width %>
          <%= poster_form.text_field :width, class: 'form_control' %>
          
          <%= poster_form.label :height %>
          <%= poster_form.text_field :height, class: 'form_control' %>
          
          <%= poster_form.label :comments %>
          <%= poster_form.text_field :comments, class: 'form_control' %>
          
          <%= poster_form.label :price_per_sqft %>
          <%= poster_form.text_field :price_per_sqft, class: 'form_control' %>
          
          <%= poster_form.label :paper_type %>
          <%= poster_form.select :paper_type, ['Satin', 'Glossy'], class: 'form_control' %>
        
      <% end %>
      
      <%= f.submit "Create Order", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/orders/viewOrders.html.erb
<% provide(:title, 'View Orders') %>
<h1>Orders</h1>

<div class="media">
   <div class="media-body">
      <table class="table table-hover">
        <thead>
           <tr>
              <th> OrderID </th>
              <th> print_location</th>
              <th> status </th>
              <th> takenby </th>
              <th colspan="5"></th>
            </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= order.id %></td>
              <td><%= order.patron_id %></td>
              <td><%= order.status %></td>
              <td><%= order.payment %></td>
              <td><%= link_to 'Edit', edit_path(:id=> order.id), class: 'btn btn-mini btn-success' %></td>
              <td><%= link_to 'Delete', order, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are You Sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/patrons/new.html.erb
<% provide(:title, 'Patron') %>
<h1>Create New Patron</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@patron, url: create_path) do |f| %>
      <%= render 'shared/patron_error_messages' %>
      
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form_control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form_control' %>
      
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form_control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form_control' %>
      
      <%= f.submit "Create Patron", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@order.errors.count, "error") %>.
    </div>
    <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_patron_error_messages.html.erb
<% if @patron.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@patron.errors.count, "error") %>.
    </div>
    <ul>
    <% @patron.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>